I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 157, in script
    define config.has_history = False
  File "renpy/common/000namespaces.rpy", line 33, in set
    setattr(self.nso, name, value)
Exception: config.has_history is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 157, in script
    define config.has_history = False
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\ast.py", line 2526, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 33, in set
    setattr(self.nso, name, value)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.has_history is not a known configuration variable.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
a_day_for_the_dead 1.0
Tue May 20 22:42:33 2025
